config:
  address: http://10.0.0.1
  login: Log In
  userNameField: loginUsername
  userName: admin
  userPasswordField: loginPassword
  userPassword: password
  deviceFile: devicesNow.json
  eventName: network_change
  apiKey: pzoBEghOg1aYYaHGEWam9HfN6wjdk3u02qIRN2kVAVN
